[package]
name = "advent-of-code"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fxhash = "0.2"
aoc-runner = "0.3"
aoc-runner-derive = "0.3"
itertools = "0.10.5"
